Repository emacs-dashboard/emacs-dashboard, pull requests merged in 2020-10, with the labels that each got.

#247 Move screenshot to new location.
  README.org
  etc/screenshot.png
Labels: minor

#246 Text startup banner.
  README.org
  dashboard-widgets.el
Labels: enhancement

#248 Use when instead if.
  dashboard.el
Labels: minor

#249 Better identify page separator.
  dashboard.el
Labels: bug

#202 Make dashboard shortcuts configurable
  dashboard-widgets.el
Labels: enhancement
