Repository emacs-dashboard/emacs-dashboard, pull requests merged in 2020-12, with the labels that each got.

#267 Respect to widget-button face.
  dashboard-widgets.el
Labels: highlighting, minor

#268 Add custom face for no items
  dashboard-widgets.el
Labels: highlighting

#272 Clarify docstring of `dashboard-projects-backend`
  dashboard-widgets.el
Labels: minor

#270 Minor clean up
  dashboard-widgets.el
Labels: minor

#273 Respect to custom items face instead of widget-button face
  README.org
  dashboard-widgets.el
Labels: enhancement

#275 feat: Agenda filter todo
  dashboard-widgets.el
Labels: agenda, enhancement

#278 Support for image transforms in newer Emacs
  dashboard-widgets.el
Labels: enhancement

#279 Add truncate style for path
  Cask
  dashboard-widgets.el
Labels: enhancement

#280 Minor fix for the patch truncate style
  dashboard-widgets.el
Labels: minor

#227 Allow moving the point during dashboard-mode-hook
  dashboard.el
Labels: enhancement

#281 Agenda highlight headlines
  dashboard-widgets.el
Labels: agenda, enhancement, highlighting

#283 Remove widget-button click.
  dashboard.el
Labels: bug
