Repository emacs-dashboard/emacs-dashboard, pull requests merged in 2021-03, with the labels that each got.

#298 Release buffers after populate agenda
  README.org
  dashboard-widgets.el
Labels: agenda

#301 Fix recent files show org agenda files issue
  dashboard.el
Labels: agenda, bug

#304 Fix CI
  dashboard.el
Labels: CI
