Repository emacs-dashboard/emacs-dashboard, pull requests merged in 2021-12, with the labels that each got.

#341 Simplify CI process
  .github/workflows/ci.yml
  Cask
  Makefile
  dashboard-widgets.el
  dashboard.el
  scripts/pkg-prepare.el
  scripts/test-pkg.bat
  scripts/test-pkg.el
  scripts/test-pkg.sh
Labels: CI

#340 Filter out archived headings from agenda items
  dashboard-widgets.el
Labels: agenda

#342 Add changelog
  CHANGELOG.md
Labels: documentation

#343 Simplify with cl-case instead of cond
  dashboard-widgets.el
Labels: minor
