Repository emacs-dashboard/emacs-dashboard, pull requests merged in 2023-02, with the labels that each got.

#436 Add ascii option to dashboard-startup-banner
  dashboard-widgets.el
Labels: enhancement

#438 Added reference to dashboard-refresh-buffer in readme file
  README.org
Labels: documentation

#441 Agenda tags format.
  README.org
  dashboard-widgets.el
Labels: agenda
